### ISSUE TITLE
1x03 Joystick C library

### ISSUE THREAD

**Issue by rickyelqasem** [SnailBarbarianMacho/MZ-700GamesProject#2]
Is it possible to make a C library so other people can use the 1x03 joystick function in z88dk program?

**Comment by SnailBarbarianMacho** [comment]
By adapting the sample code provided by Sharp to the z88dk calling convention, it would be possible to make it into a library.
However, I am busy with my main job and my new game...

**Comment by SnailBarbarianMacho** [comment]
By adapting the sample code provided by Sharp to the z88dk calling convention, it would be possible to make it into a library.
However, I am busy with my main job and my new game...

**Comment by SnailBarbarianMacho** [comment]
By adapting the sample code provided by Sharp to the z88dk calling convention, it would be possible to make it into a library.
However, I am busy with my main job and my new game...
